id: polarishub/polaris-adme-fang-rppb-1
name: adme-fang-RPPB-1
task_type: drug_discovery
domain: molecular_properties
difficulty: medium
awards_medals: true
prizes: null
description: biomlbench/tasks/polarishub/polaris-adme-fang-rppb-1/description.md
preparer: biomlbench.tasks.polarishub.polaris-adme-fang-rppb-1.prepare:prepare

data_source:
  type: polaris
  benchmark_id: polaris/adme-fang-rppb-1

datasets:
  '0':
    answers: answers.csv
    sample_submission: sample_submission.csv

grader:
  name: polaris-metric
  grade_fn: biomlbench.tasks.polarishub.polaris-adme-fang-rppb-1.grade:grade

biomedical_metadata:
  modality: molecular
  data_type: single_task
  clinical_relevance: drug_discovery
  polaris_main_metric: pearsonr

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
