
id: proteingym-dms/ISDH_STAAW_Tsuboyama_2023_2LHR
name: ISDH_STAAW_Tsuboyama_2023_2LHR
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/ISDH_STAAW_Tsuboyama_2023_2LHR/description.md
preparer: biomlbench.tasks.proteingym-dms.ISDH_STAAW_Tsuboyama_2023_2LHR.prepare:prepare
time_limit: 14400  # 4 hours

data_source:
  type: proteingym-dms
  benchmark_id: ISDH_STAAW_Tsuboyama_2023_2LHR

dataset:
  answers: proteingym-dms/ISDH_STAAW_Tsuboyama_2023_2LHR/prepared/private/answers.csv
  sample_submission: proteingym-dms/ISDH_STAAW_Tsuboyama_2023_2LHR/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.ISDH_STAAW_Tsuboyama_2023_2LHR.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 1944

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
