id: kaggle/rsna-2022-cervical-spine-fracture-detection
name: RSNA 2022 Cervical Spine Fracture Detection
competition_type: code
awards_medals: true
prizes:
  - position: 1
    value: 6000
  - position: 2
    value: 5000
  - position: 3
    value: 4000
  - position: 4
    value: 3000
  - position: 5
    value: 3000
  - position: 6
    value: 3000
  - position: 7
    value: 3000
  - position: 8
    value: 3000
description: biomlbench/tasks/kaggle/rsna-2022-cervical-spine-fracture-detection/description.md

dataset:
  answers: kaggle/rsna-2022-cervical-spine-fracture-detection/prepared/private/answers.csv
  sample_submission: kaggle/rsna-2022-cervical-spine-fracture-detection/prepared/public/sample_submission.csv

data_source:
  type: kaggle
  benchmark_id: kaggle/rsna-2022-cervical-spine-fracture-detection


grader:
  name: weighted-multi-label-log-loss
  grade_fn: biomlbench.tasks.kaggle.rsna-2022-cervical-spine-fracture-detection.grade:grade

preparer: biomlbench.tasks.kaggle.rsna-2022-cervical-spine-fracture-detection.prepare:prepare
