defaults: &defaults
  start: aide/start.sh
  dockerfile: aide/Dockerfile
  kwargs_type: omegaconf
  env_vars: &env_vars
    TIME_LIMIT_SECS: ${{ env.BMLB_TIME_LIMIT_SECS }}
    STEP_LIMIT: ${{ env.BMLB_STEP_LIMIT }}

kwargs_common: &kwargs_common
  agent.steps: ${{ env.BMLB_STEP_LIMIT }}
  exec.timeout: 3600 # time limit per step

aide:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: ${{ env.OPENROUTER_MODEL }}
    agent.feedback.model: ${{ env.OPENROUTER_MODEL }}
  env_vars:
    <<: *env_vars
    OPENAI_API_KEY: ${{ env.OPENROUTER_API_KEY }}
    OPENAI_BASE_URL: ${{ env.OPENROUTER_BASE_URL }}
    http_proxy: ${{ env.http_proxy }}
    https_proxy: ${{ env.https_proxy }}
    HTTP_PROXY: ${{ env.HTTP_PROXY }}
    HTTPS_PROXY: ${{ env.HTTPS_PROXY }}
