vars:
  step_count: &step_count 50
  time_limit: &time_limit 43200 # total time limit

defaults: &defaults
  start: aide/start.sh
  dockerfile: aide/Dockerfile
  kwargs_type: omegaconf
  env_vars: &env_vars
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count

kwargs_common: &kwargs_common
  agent.steps: *step_count
  exec.timeout: 4320 # time limit per step

aide:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: gpt-5-2025-08-07
    agent.feedback.model: gpt-5-2025-08-07
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aide/dev:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: gpt-5-2025-08-07
    agent.feedback.model: gpt-5-2025-08-07
    agent.steps: 8
  env_vars:
    <<: *env_vars
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aide/o1-preview:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: o1-preview
    agent.feedback.model: gpt-5-2025-08-07
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}


aide/claude-3-5-sonnet:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: claude-3-5-sonnet-20240620
    agent.feedback.model: gpt-5-2025-08-07
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

aide/gemini-1.5-pro:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: gemini-1.5-pro-002
    agent.feedback.model: gpt-5-2025-08-07
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
