vars:
  step_count: &step_count 2000
  time_limit: &time_limit 43200 # total time limit

defaults: &defaults
  start: aide/start.sh
  dockerfile: aide/Dockerfile
  kwargs_type: omegaconf
  env_vars: &env_vars
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count

kwargs_common: &kwargs_common
  agent.steps: *step_count
  exec.timeout: 3600 # time limit per step

aide:
  <<: *defaults
  kwargs:
    <<: *kwargs_common
    agent.code.model: gpt-4.1-2025-04-14
    agent.feedback.model: gpt-4.1-2025-04-14
    agent.steps: *step_count
  env_vars:
    <<: *env_vars
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
