autobioml:
  start: autobioml/start.sh
  dockerfile: autobioml/Dockerfile
  kwargs_type: argparse
  kwargs:
    model: gpt-4.1
    max_iterations: 50
    enable_public_evaluation: false
  env_vars:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
