id: polarishub/mlls-bend-zeroshot-variant-effects-disease
name: "bend-zeroshot-variant-effects-disease"
task_type: drug_discovery
domain: molecular_properties
difficulty: medium
awards_medals: true
prizes: null
description: biomlbench/tasks/polarishub/mlls-bend-zeroshot-variant-effects-disease/description.md

data_source:
  type: polaris
  benchmark_id: mlls/bend-zeroshot-variant-effects-disease

dataset:
  answers: polarishub/mlls-bend-zeroshot-variant-effects-disease/prepared/private/answers.csv
  sample_submission: polarishub/mlls-bend-zeroshot-variant-effects-disease/prepared/public/sample_submission.csv

grader:
  name: polaris-metric
  grade_fn: biomlbench.tasks.polarishub.mlls-bend-zeroshot-variant-effects-disease.grade:grade

preparer: biomlbench.tasks.polarishub.mlls-bend-zeroshot-variant-effects-disease.prepare:prepare

biomedical_metadata:
  modality: "molecular"
  data_type: "single_task"
  clinical_relevance: "drug_discovery"
  polaris_main_metric: "roc_auc"

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
