id: vinbigdata-chest-xray-abnormalities-detection
name: VinBigData Chest X-ray Abnormalities Detection
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 20000
  - position: 2
    value: 14000
  - position: 3
    value: 8000
  - position: Special Prize
    value: 8000
description: biomlbench/tasks/kaggle/vinbigdata-chest-xray-abnormalities-detection/description.md

datasets:
  '0':
    answers: answers.csv
    sample_submission: sample_submission.csv

grader:
  name: mAP-at-IoU>0.4
  grade_fn: biomlbench.tasks.kaggle.vinbigdata-chest-xray-abnormalities-detection.grade:grade

preparer: biomlbench.tasks.kaggle.vinbigdata-chest-xray-abnormalities-detection.prepare:prepare
