
id: proteingym-dms/RASK_HUMAN_Weng_2022_binding-DARPin_K55
name: RASK_HUMAN_Weng_2022_binding-DARPin_K55
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/RASK_HUMAN_Weng_2022_binding-DARPin_K55/description.md
preparer: biomlbench.tasks.proteingym-dms.RASK_HUMAN_Weng_2022_binding-DARPin_K55.prepare:prepare
time_limit: 28800  # 8 hours

data_source:
  type: proteingym-dms
  benchmark_id: RASK_HUMAN_Weng_2022_binding-DARPin_K55

dataset:
  answers: proteingym-dms/RASK_HUMAN_Weng_2022_binding-DARPin_K55/prepared/private/answers.csv
  sample_submission: proteingym-dms/RASK_HUMAN_Weng_2022_binding-DARPin_K55/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.RASK_HUMAN_Weng_2022_binding-DARPin_K55.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 24873

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
