
id: proteingym-dms/RFAH_ECOLI_Tsuboyama_2023_2LCL
name: RFAH_ECOLI_Tsuboyama_2023_2LCL
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/RFAH_ECOLI_Tsuboyama_2023_2LCL/description.md
preparer: biomlbench.tasks.proteingym-dms.RFAH_ECOLI_Tsuboyama_2023_2LCL.prepare:prepare
time_limit: 28800  # 8 hours

data_source:
  type: proteingym-dms
  benchmark_id: RFAH_ECOLI_Tsuboyama_2023_2LCL

dataset:
  answers: proteingym-dms/RFAH_ECOLI_Tsuboyama_2023_2LCL/prepared/private/answers.csv
  sample_submission: proteingym-dms/RFAH_ECOLI_Tsuboyama_2023_2LCL/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.RFAH_ECOLI_Tsuboyama_2023_2LCL.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 1326

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
