id: polarishub/biogen-adme-fang-rppb-reg-v1
name: "adme-fang-RPPB-reg-v1"
task_type: drug_discovery
domain: molecular_properties
difficulty: medium
awards_medals: true
prizes: null
description: biomlbench/tasks/polarishub/biogen-adme-fang-rppb-reg-v1/description.md

data_source:
  type: polaris
  benchmark_id: biogen/adme-fang-rppb-reg-v1

dataset:
  answers: polarishub/biogen-adme-fang-rppb-reg-v1/prepared/private/answers.csv
  sample_submission: polarishub/biogen-adme-fang-rppb-reg-v1/prepared/public/sample_submission.csv

grader:
  name: polaris-metric
  grade_fn: biomlbench.tasks.polarishub.biogen-adme-fang-rppb-reg-v1.grade:grade

preparer: biomlbench.tasks.polarishub.biogen-adme-fang-rppb-reg-v1.prepare:prepare

biomedical_metadata:
  modality: "molecular"
  data_type: "single_task"
  clinical_relevance: "drug_discovery"
  polaris_main_metric: "pearsonr"

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
