vars:
  time_limit: &time_limit 43200 
  step_count: &step_count 2000

mlagentbench:
  start: mlagentbench/start.sh
  dockerfile: mlagentbench/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for MLAgentBench.runner
    llm-name: gpt-4.1-2025-04-14
    edit-script-llm-name: gpt-4.1-2025-04-14
    fast-llm-name: gpt-4.1-2025-04-14
    max-steps: *step_count
    agent-max-steps: *step_count # Some MLAB agents have their own max-steps which is separate from the env max-steps; for ResearchAgent, these should be the same
    max-time: *time_limit
    max-retries: 10 # retry if the agent doesn't give a valid action response
  env_vars:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    TIME_LIMIT_SECS: *time_limit
    STEP_LIMIT: *step_count
