mlagentbench:
  start: mlagentbench/start.sh
  dockerfile: mlagentbench/Dockerfile
  kwargs_type: argparse
  kwargs: # Args for MLAgentBench.runner
    llm-name: ${{ env.OPENROUTER_MODEL }}
    edit-script-llm-name: ${{ env.OPENROUTER_MODEL }}
    fast-llm-name: ${{ env.OPENROUTER_MODEL }}
    max-steps: ${{ env.BMLB_STEP_LIMIT }}
    agent-max-steps: ${{ env.BMLB_STEP_LIMIT }}
    max-time: ${{ env.BMLB_TIME_LIMIT_SECS }}
    max-retries: 10 # retry if the agent doesn't give a valid action response
  env_vars:
    OPENAI_API_KEY: ${{ env.OPENROUTER_API_KEY }}
    OPENAI_BASE_URL: ${{ env.OPENROUTER_BASE_URL }}
    TIME_LIMIT_SECS: ${{ env.BMLB_TIME_LIMIT_SECS }}
    STEP_LIMIT: ${{ env.BMLB_STEP_LIMIT }}
