
id: proteingym-dms/YNZC_BACSU_Tsuboyama_2023_2JVD
name: YNZC_BACSU_Tsuboyama_2023_2JVD
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/YNZC_BACSU_Tsuboyama_2023_2JVD/description.md
preparer: biomlbench.tasks.proteingym-dms.YNZC_BACSU_Tsuboyama_2023_2JVD.prepare:prepare
time_limit: 28800  # 8 hours

data_source:
  type: proteingym-dms
  benchmark_id: YNZC_BACSU_Tsuboyama_2023_2JVD

dataset:
  answers: proteingym-dms/YNZC_BACSU_Tsuboyama_2023_2JVD/prepared/private/answers.csv
  sample_submission: proteingym-dms/YNZC_BACSU_Tsuboyama_2023_2JVD/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.YNZC_BACSU_Tsuboyama_2023_2JVD.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 2300

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
