
id: proteingym-dms/DOCK1_MOUSE_Tsuboyama_2023_2M0Y
name: DOCK1_MOUSE_Tsuboyama_2023_2M0Y
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/DOCK1_MOUSE_Tsuboyama_2023_2M0Y/description.md
preparer: biomlbench.tasks.proteingym-dms.DOCK1_MOUSE_Tsuboyama_2023_2M0Y.prepare:prepare
time_limit: 14400  # 4 hours

data_source:
  type: proteingym-dms
  benchmark_id: DOCK1_MOUSE_Tsuboyama_2023_2M0Y

dataset:
  answers: proteingym-dms/DOCK1_MOUSE_Tsuboyama_2023_2M0Y/prepared/private/answers.csv
  sample_submission: proteingym-dms/DOCK1_MOUSE_Tsuboyama_2023_2M0Y/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.DOCK1_MOUSE_Tsuboyama_2023_2M0Y.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 2915

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
