id: polarishub/tdcommons-caco2-wang
name: "caco2-wang"
task_type: drug_discovery
domain: molecular_properties
difficulty: medium
awards_medals: true
prizes: null
description: biomlbench/tasks/polarishub/tdcommons-caco2-wang/description.md
time_limit: 28800  # 8 hours
# time_limit: 120

data_source:
  type: polaris
  benchmark_id: tdcommons/caco2-wang

dataset:
  answers: polarishub/tdcommons-caco2-wang/prepared/private/answers.csv
  sample_submission: polarishub/tdcommons-caco2-wang/prepared/public/sample_submission.csv

grader:
  name: polaris-metric
  grade_fn: biomlbench.tasks.polarishub.tdcommons-caco2-wang.grade:grade

preparer: biomlbench.tasks.polarishub.tdcommons-caco2-wang.prepare:prepare

biomedical_metadata:
  modality: "molecular"
  data_type: "single_task"
  clinical_relevance: "drug_discovery"
  polaris_main_metric: "mean_absolute_error"

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
