
id: proteingym-dms/SDA_BACSU_Tsuboyama_2023_1PV0
name: SDA_BACSU_Tsuboyama_2023_1PV0
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/SDA_BACSU_Tsuboyama_2023_1PV0/description.md
preparer: biomlbench.tasks.proteingym-dms.SDA_BACSU_Tsuboyama_2023_1PV0.prepare:prepare

data_source:
  type: proteingym-dms
  benchmark_id: SDA_BACSU_Tsuboyama_2023_1PV0

dataset:
  answers: proteingym-dms/SDA_BACSU_Tsuboyama_2023_1PV0/prepared/private/answers.csv
  sample_submission: proteingym-dms/SDA_BACSU_Tsuboyama_2023_1PV0/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.SDA_BACSU_Tsuboyama_2023_1PV0.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 2770

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
