
id: proteingym-dms/PSAE_PICP2_Tsuboyama_2023_1PSE
name: PSAE_PICP2_Tsuboyama_2023_1PSE
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/PSAE_PICP2_Tsuboyama_2023_1PSE/description.md
preparer: biomlbench.tasks.proteingym-dms.PSAE_PICP2_Tsuboyama_2023_1PSE.prepare:prepare
time_limit: 14400  # 4 hours

data_source:
  type: proteingym-dms
  benchmark_id: PSAE_PICP2_Tsuboyama_2023_1PSE

dataset:
  answers: proteingym-dms/PSAE_PICP2_Tsuboyama_2023_1PSE/prepared/private/answers.csv
  sample_submission: proteingym-dms/PSAE_PICP2_Tsuboyama_2023_1PSE/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.PSAE_PICP2_Tsuboyama_2023_1PSE.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 1579

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
