
id: proteingym-dms/RAD_ANTMA_Tsuboyama_2023_2CJJ
name: RAD_ANTMA_Tsuboyama_2023_2CJJ
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/RAD_ANTMA_Tsuboyama_2023_2CJJ/description.md
preparer: biomlbench.tasks.proteingym-dms.RAD_ANTMA_Tsuboyama_2023_2CJJ.prepare:prepare
time_limit: 28800  # 8 hours

data_source:
  type: proteingym-dms
  benchmark_id: RAD_ANTMA_Tsuboyama_2023_2CJJ

dataset:
  answers: proteingym-dms/RAD_ANTMA_Tsuboyama_2023_2CJJ/prepared/private/answers.csv
  sample_submission: proteingym-dms/RAD_ANTMA_Tsuboyama_2023_2CJJ/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.RAD_ANTMA_Tsuboyama_2023_2CJJ.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 912

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
