
id: proteingym-dms/SPG2_STRSG_Tsuboyama_2023_5UBS
name: SPG2_STRSG_Tsuboyama_2023_5UBS
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/SPG2_STRSG_Tsuboyama_2023_5UBS/description.md
preparer: biomlbench.tasks.proteingym-dms.SPG2_STRSG_Tsuboyama_2023_5UBS.prepare:prepare
time_limit: 14400  # 4 hours

data_source:
  type: proteingym-dms
  benchmark_id: SPG2_STRSG_Tsuboyama_2023_5UBS

dataset:
  answers: proteingym-dms/SPG2_STRSG_Tsuboyama_2023_5UBS/prepared/private/answers.csv
  sample_submission: proteingym-dms/SPG2_STRSG_Tsuboyama_2023_5UBS/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.SPG2_STRSG_Tsuboyama_2023_5UBS.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 1451

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
