id: kaggle/uw-madison-gi-tract-image-segmentation
name: UW-Madison GI Tract Image Segmentation
competition_type: code
awards_medals: true
prizes:
  - position: 1
    value: 1200
  - position: 2
    value: 8000
  - position: 3
    value: 5000
description: biomlbench/tasks/kaggle/uw-madison-gi-tract-image-segmentation/description.md
time_limit: 43200  # 12 hours

dataset:
  answers: kaggle/uw-madison-gi-tract-image-segmentation/prepared/private/answers.csv
  sample_submission: kaggle/uw-madison-gi-tract-image-segmentation/prepared/public/sample_submission.csv

data_source:
  type: kaggle
  benchmark_id: kaggle/uw-madison-gi-tract-image-segmentation


grader:
  name: dice-hausdorff-combo
  grade_fn: biomlbench.tasks.kaggle.uw-madison-gi-tract-image-segmentation.grade:grade

preparer: biomlbench.tasks.kaggle.uw-madison-gi-tract-image-segmentation.prepare:prepare
