
id: proteingym-dms/DNJA1_HUMAN_Tsuboyama_2023_2LO1
name: DNJA1_HUMAN_Tsuboyama_2023_2LO1
task_type: fitness_prediction
domain: protein_engineering
difficulty: medium
awards_medals: false
prizes: null
description: biomlbench/tasks/proteingym-dms/DNJA1_HUMAN_Tsuboyama_2023_2LO1/description.md
preparer: biomlbench.tasks.proteingym-dms.DNJA1_HUMAN_Tsuboyama_2023_2LO1.prepare:prepare
time_limit: 28800  # 8 hours

data_source:
  type: proteingym-dms
  benchmark_id: DNJA1_HUMAN_Tsuboyama_2023_2LO1

dataset:
  answers: proteingym-dms/DNJA1_HUMAN_Tsuboyama_2023_2LO1/prepared/private/answers.csv
  sample_submission: proteingym-dms/DNJA1_HUMAN_Tsuboyama_2023_2LO1/prepared/public/sample_submission.csv

grader:
  name: proteingym-metric
  grade_fn: biomlbench.tasks.proteingym-dms.DNJA1_HUMAN_Tsuboyama_2023_2LO1.grade:grade

biomedical_metadata:
  modality: protein_sequence
  data_type: single_task
  proteingym_main_metric: spearman
  num_sequences: 2264

compute_requirements:
  recommended_gpu_memory_gb: 4
  estimated_runtime_minutes: 15
  max_dataset_size_gb: 2
