vars:
  step_count: &step_count 2000
  time_limit: &time_limit 43200 # total time limit

biomni:
  start: biomni/start.sh
  dockerfile: biomni/Dockerfile
  kwargs_type: argparse
  kwargs:
    llm: ${{ env.OPENROUTER_MODEL }}
    timeout_seconds: ${{ env.BIOMNI_TIMEOUT_SECONDS }}
  env_vars:
    TIME_LIMIT_SECS: ${{ env.BMLB_TIME_LIMIT_SECS }}
    STEP_LIMIT: ${{ env.BMLB_STEP_LIMIT }}
    OPENROUTER_API_KEY: ${{ env.OPENROUTER_API_KEY }}
    OPENROUTER_BASE_URL: ${{ env.OPENROUTER_BASE_URL }}
    BIOMNI_SOURCE: ${{ env.BIOMNI_SOURCE }}
    BIOMNI_LLM_MODEL: ${{ env.BIOMNI_LLM_MODEL }}
    BIOMNI_CUSTOM_BASE_URL: ${{ env.BIOMNI_CUSTOM_BASE_URL }}
    BIOMNI_CUSTOM_API_KEY: ${{ env.BIOMNI_CUSTOM_API_KEY }}
    http_proxy: ${{ env.http_proxy }}
    https_proxy: ${{ env.https_proxy }}
    HTTP_PROXY: ${{ env.HTTP_PROXY }}
    HTTPS_PROXY: ${{ env.HTTPS_PROXY }}
    no_proxy: ${{ env.no_proxy }}
    NO_PROXY: ${{ env.NO_PROXY }}
