biomni:
  start: biomni/start.sh
  dockerfile: biomni/Dockerfile
  kwargs_type: argparse
  kwargs:
    llm: ${{ env.OPENROUTER_MODEL }}
  env_vars:
    TIME_LIMIT_SECS: ${{ env.BMLB_TIME_LIMIT_SECS }}
    STEP_LIMIT: ${{ env.BMLB_STEP_LIMIT }}
    LLM_SOURCE: ${{ env.LLM_SOURCE }}
    CUSTOM_MODEL_BASE_URL: ${{ env.CUSTOM_MODEL_BASE_URL }}
    CUSTOM_MODEL_API_KEY: ${{ env.CUSTOM_MODEL_API_KEY }}
